# Generated by Django 2.0.6 on 2018-10-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20181023_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preference1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref1', to='students.Project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preference2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref2', to='students.Project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preference3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref3', to='students.Project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preference4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref4', to='students.Project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='project_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedProj', to='students.Project'),
        ),
    ]
