# Generated by Django 2.1.2 on 2018-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20181024_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.BinaryField(blank=True),
        ),
    ]
