# Generated by Django 2.1.2 on 2018-10-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20181024_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedProj', to='students.Project'),
        ),
    ]
