# Generated by Django 2.0.6 on 2018-10-31 18:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20181031_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='filename',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='files/<django.db.models.fields.CharField>'), upload_to=''),
        ),
    ]
